// <auto-generated />
namespace projekt_car_sellers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bazaDanych : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bazaDanych));
        
        string IMigrationMetadata.Id
        {
            get { return "201305021622324_bazaDanych"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
